# Generated by Django 4.2.1 on 2024-10-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message', models.TextField(max_length=2500, null=True, verbose_name='Сообщение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=200, verbose_name='Наименование блюда')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Состав')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('is_available', models.BooleanField(choices=[(0, 'Отсутствует'), (1, 'Вналичие')], default=1, verbose_name='Наличие')),
                ('image', models.ImageField(blank=True, default='Добавить изображение', upload_to='products/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в меню')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='restaurant_website.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name_product',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
